# Generated by Django 3.1.1 on 2020-10-19 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=64)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=1)),
                ('title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.projects')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
