# Generated by Django 3.1.1 on 2020-10-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201027_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.ManyToManyField(to='todo.Projects'),
        ),
    ]
